---
title: "solubility_binary"
author: "Alicia Key"
date: "7/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(readr)
library(skimr)
library(printr)
library(ggplot2)
library(tidyr)
library(gridExtra)
```

## Solubility Data
``` {r message = FALSE, include = FALSE}
binarySolubility <- read_csv("data/delaney-binary.csv")
train <- binarySolubility %>%
  select(Molecular.Weight, 
         Number.of.Rotatable.Bonds, 
         Polar.Surface.Area,
         solubility.above.or.below.median) %>%
  mutate_at(.vars = "solubility.above.or.below.median", .funs = factor)
```

### Summary

``` {r echo = FALSE}
summary(train)
```

### Classes

There are two classes stored in the variable `solubility.above.or.below.median`. 1 means the solubility is above the median, 0 means the solubility is below the median. The underlying solubility is measured in units of log(g/mol). Class counts are as follows:

``` {r echo = FALSE}
train %>%
  count(solubility.above.or.below.median)
```

### Distributions of predictor variables

``` {r, fig.height = 2, fig.width = 7, fig.align = "center", echo = FALSE}
p1 <- ggplot(train, aes(x = Molecular.Weight)) +
  geom_histogram(bins = 10) +
  ylim(0, 600) +
  ggtitle("Molecular Weight") +
  xlab("g/mol")

p2 <- ggplot(train, aes(x = Number.of.Rotatable.Bonds)) +
  geom_histogram(bins = 10) +
  ylim(0, 600) +
  ggtitle("Rotatable Bonds") +
  xlab("bonds")

p3 <- ggplot(train, aes(x = Polar.Surface.Area)) +
  geom_histogram(bins = 10) +
  ylim(0, 600) +
  ggtitle("Polar Surface Area") +
  xlab("sq. angstroms")

grid.arrange(p1, p2, p3, nrow = 1)
```
