---
title: "Solubility Unsupervised"
author: "Alicia Key"
date: "1/23/2021"
output: html_document
---

```{r setup, include=TRUE, echo = FALSE, warning = FALSE, message = FALSE, fig.align = "center"}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(readr)
library(dplyr)
library(tidyr)
library(gridExtra)
```

## Load the data set

``` {r}
df <- as_tibble(read.csv("data/delaney-processed.csv")) %>%
  select(
    compound = Compound.ID, 
    mw = Molecular.Weight, 
    h_bond_donors = Number.of.H.Bond.Donors, 
    rings = Number.of.Rings, 
    rotatable_bonds = Number.of.Rotatable.Bonds, 
    psa = Polar.Surface.Area, 
    solubility = measured.log.solubility.in.mols.per.litre
)
```

## Extract a matrix

``` {r}
compound_matrix <- df %>%
  select(!c("compound", "solubility")) %>%
  as.matrix()

row.names(compound_matrix) <- df$compound
```

## Run PCA on all the numeric attributes

``` {r}
compound_pca <- prcomp(compound_matrix, scale. = TRUE, center = TRUE)
summary(compound_pca)
```

## Create the plots to explore the PCA

First the biplot

``` {r}
biplot(compound_pca)
```

Now the scree plots

``` {r, fig.caption = "}
pca_pve_df <- tibble(
  principal_component = 1:length(compound_pca_pve),
  proportion_variance_explained = compound_pca_pve,
  cumulative_variance_explained = cumsum(compound_pca_pve)
)

p1 <- ggplot(pca_pve_df, aes(x = principal_component, y = proportion_variance_explained)) +
  geom_line() +
  geom_point(shape = 19, size = 3) +
  ylim(c(0, 1)) +
  labs(x = "principal component",
       y = "proportion of variance explained") +
  theme_minimal()

p2 <- ggplot(pca_pve_df, aes(x = principal_component, y = cumulative_variance_explained)) +
  geom_line() +
  geom_point(shape = 19, size = 3) +
  ylim(c(0, 1)) +
  labs(x = "principal component",
       y = "cumulative proportion of variance explained") +
  theme_minimal()

grid.arrange(p1, p2, nrow = 1)
```