---
title: "solubility_regression_functions"
author: "Alicia Key"
date: "1/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(dplyr)
library(tidyr)
library(broom)
library(ggplot2)
library(ranger)
```

Read in the main dataframe and rename the columns

``` {r}
df <- as_tibble(read.csv("data/delaney-processed.csv")) %>%
  select(
    compound = Compound.ID, 
    mw = Molecular.Weight, 
    h_bond_donors = Number.of.H.Bond.Donors, 
    rings = Number.of.Rings, 
    rotatable_bonds = Number.of.Rotatable.Bonds, 
    psa = Polar.Surface.Area, 
    solubility = measured.log.solubility.in.mols.per.litre,
    minimum_degree = Minimum.Degree
)
```

Now define a few functions to run the analysis

``` {r}
solubilityTrainTestSplit <- function(all_data, split_fraction = 0.75, random_seed = 13) {
  # Shuffle based on random seed
  set.seed(random_seed)
  sample_indecies <- sample(nrow(all_data), nrow(all_data))
  shuffled <- all_data[sample_indecies, ]
  
  # Train test split
  train_row <- round(nrow(shuffled) * split_fraction)
  test_row <- train_row + 1
  train <- shuffled[1:train_row, ]
  test <- shuffled[test_row:nrow(shuffled), ]
  
  # Now create the final list that is returned
  list(
    train = train,
    test = test
  )
}

analyzeSolubilityLinearModel <- function(model, test_data) {
  # Run the prediction
  predicted_solbilities <- predict(model, test_data)
  
  # Assemble the compounds and predictions back onto the
  # train features
  
  test_results <- test_data %>%
    mutate(prediction = predicted_solbilities) %>%
    mutate(residual = solubility - prediction)
  
  # Calculate the standard deviation and RMSE
  sd_solubilities <- sd(test_results$solubility)
  rmse <- sqrt(mean(test_results$residual ^ 2))
  
  # calculate r_squared
  rss <- sum(test_results$residual ^ 2)
  total_error <- test_results$solubility - mean(test_results$solubility)
  tss <- sum(total_error ^ 2)
  r_squared <- 1 - (rss / tss)
  
  # Create a list to return to the caller
  list(
    sd_solubilities = sd_solubilities,
    rmse = rmse,
    test_results = test_results,
    r_squared = r_squared
  )
}

analyzeSolubilityRandomForestModel <- function(model, test_data) {
  # Run the prediction
  predicted_solbilities <- predict(model, test_data)$predictions
  
  # Assemble the compounds and predictions back onto the
  # train features
  
  test_results <- test_data %>%
    mutate(prediction = predicted_solbilities) %>%
    mutate(residual = solubility - prediction)
  
  # Calculate the standard deviation and RMSE
  sd_solubilities <- sd(test_results$solubility)
  rmse <- sqrt(mean(test_results$residual ^ 2))
  
  # calculate r_squared
  rss <- sum(test_results$residual ^ 2)
  total_error <- test_results$solubility - mean(test_results$solubility)
  tss <- sum(total_error ^ 2)
  r_squared <- 1 - (rss / tss)
  
  # Create a list to return to the caller
  list(
    sd_solubilities = sd_solubilities,
    rmse = rmse,
    test_results = test_results,
    r_squared = r_squared
  )
}
```

Do the train test split

``` {r}
split <- solubilityTrainTestSplit(df)
test <- split$test
train <- split$train
```

## Baseline model

Simple linear model, all predictors.

``` {r}
lm_everything_model <- lm(solubility ~ mw + h_bond_donors + rings + rotatable_bonds + psa + minimum_degree, train)
lm_everything_result <- analyzeSolubilityLinearModel(lm_everything_model, test)
lm_everything_result
```

## Random forest model

Now try a random forest model on these data. Use all the predictors

``` {r}
rf_everything_model <- ranger(
  solubility ~ mw + h_bond_donors + rings + rotatable_bonds + psa + minimum_degree,
  train,
  num.trees = 500,
  respect.unordered.factors = "order"
)
rf_everything_result <- analyzeSolubilityRandomForestModel(rf_everything_model, test)
rf_everything_result
```

# Some exploratory visual analytics

``` {r}
ggplot(df, aes(x = mw)) +
  geom_histogram(bins = 10)

ggplot(df, aes(x = psa)) +
  geom_histogram(bins = 10)

ggplot(df, aes(x = solubility)) +
  geom_histogram(bins = 10)

ggplot(df, aes(x = h_bond_donors)) +
  geom_bar()

ggplot(df, aes(x = rings)) +
  geom_bar()

ggplot(df, aes(x = rotatable_bonds)) +
  geom_bar()

ggplot(df, aes(x = minimum_degree)) +
  geom_bar()
```

